using Employee_Attendance_Salary_Management.Models;
using Npgsql;
using NpgsqlTypes;

namespace Employee_Attendance_Salary_Management.Services;

public sealed class AttendanceService
{
    public async Task<IReadOnlyList<HolidayCalendarItem>> GetCalendarsAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("SELECT x.id,x.branch_id,b.name,x.code,x.name,x.is_active FROM attendance.holiday_calendar x LEFT JOIN core.branch b ON b.id=x.branch_id ORDER BY x.is_active DESC,lower(x.name)",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<HolidayCalendarItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),G(r,1),T(r,2),r.GetString(3),r.GetString(4),r.GetBoolean(5)));return a;}
    public async Task<IReadOnlyList<HolidayItem>> GetHolidaysAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("SELECT h.id,h.calendar_id,c.name,h.holiday_date,h.name,h.is_paid FROM attendance.holiday h JOIN attendance.holiday_calendar c ON c.id=h.calendar_id ORDER BY h.holiday_date DESC",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<HolidayItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetFieldValue<DateOnly>(3),r.GetString(4),r.GetBoolean(5)));return a;}
    public async Task<IReadOnlyList<ShiftItem>> GetShiftsAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("SELECT id,code,name,start_local_time,end_local_time,break_minutes,crosses_midnight,scheduled_minutes,is_flexible,is_active FROM attendance.shift ORDER BY is_active DESC,lower(name)",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<ShiftItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetFieldValue<TimeOnly>(3),r.GetFieldValue<TimeOnly>(4),r.GetInt32(5),r.GetBoolean(6),r.GetInt32(7),r.GetBoolean(8),r.GetBoolean(9)));return a;}
    public async Task<IReadOnlyList<AttendancePolicyItem>> GetPoliciesAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("SELECT id,code,name,late_grace_minutes,early_out_grace_minutes,half_day_below_minutes,absent_below_minutes,overtime_after_minutes,overtime_rounding_minutes,overtime_multiplier,holiday_overtime_multiplier,weekly_off_days,require_overtime_approval,is_active FROM attendance.attendance_policy ORDER BY is_active DESC,lower(name)",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<AttendancePolicyItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetInt32(3),r.GetInt32(4),NI(r,5),NI(r,6),r.GetInt32(7),r.GetInt32(8),r.GetDecimal(9),r.GetDecimal(10),r.GetFieldValue<short[]>(11),r.GetBoolean(12),r.GetBoolean(13)));return a;}
    public async Task<IReadOnlyList<EmployeeScheduleItem>> GetSchedulesAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("""SELECT s.id,s.employee_id,concat_ws(' ',e.first_name,e.last_name),e.employee_no,s.shift_id,sh.name,s.policy_id,p.name,s.holiday_calendar_id,h.name,s.effective_from,s.effective_to FROM attendance.employee_schedule s JOIN hr.employee e ON e.id=s.employee_id JOIN attendance.shift sh ON sh.id=s.shift_id JOIN attendance.attendance_policy p ON p.id=s.policy_id LEFT JOIN attendance.holiday_calendar h ON h.id=s.holiday_calendar_id ORDER BY s.effective_from DESC,lower(e.first_name)""",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<EmployeeScheduleItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetGuid(4),r.GetString(5),r.GetGuid(6),r.GetString(7),G(r,8),T(r,9),r.GetFieldValue<DateOnly>(10),ND(r,11)));return a;}
    public async Task<IReadOnlyList<AttendanceDayItem>> GetDaysAsync(DateOnly from,DateOnly to,CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("""SELECT a.id,a.employee_id,concat_ws(' ',e.first_name,e.last_name),e.employee_no,b.name,d.name,a.work_date,a.first_in_at,a.last_out_at,a.scheduled_minutes,a.worked_minutes,a.late_minutes,a.early_out_minutes,a.overtime_minutes,a.break_minutes,a.status,a.entry_source,a.notes FROM attendance.attendance_day a JOIN hr.employee e ON e.id=a.employee_id JOIN core.branch b ON b.id=a.branch_id JOIN core.department d ON d.id=a.department_id WHERE a.work_date BETWEEN @from AND @to ORDER BY a.work_date DESC,lower(e.first_name)""",c);q.Parameters.AddWithValue("from",from);q.Parameters.AddWithValue("to",to);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<AttendanceDayItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetFieldValue<DateOnly>(6),DTO(r,7),DTO(r,8),r.GetInt32(9),r.GetInt32(10),r.GetInt32(11),r.GetInt32(12),r.GetInt32(13),r.GetInt32(14),r.GetString(15),r.GetString(16),T(r,17)));return a;}
    public async Task<IReadOnlyList<AttendanceRequestItem>> GetRequestsAsync(CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand("""SELECT id,kind,employee_id,employee_name,employee_no,branch_name,work_date,requested_first_in_at,requested_last_out_at,requested_minutes,approved_minutes,multiplier,reason,status,requested_by,created_at FROM (SELECT a.id,'adjustment' kind,a.employee_id,concat_ws(' ',e.first_name,e.last_name) employee_name,e.employee_no,b.name branch_name,a.work_date,a.requested_first_in_at,a.requested_last_out_at,NULL::int requested_minutes,NULL::int approved_minutes,NULL::numeric multiplier,a.reason,a.status,u.display_name requested_by,a.created_at FROM attendance.adjustment_request a JOIN hr.employee e ON e.id=a.employee_id JOIN core.branch b ON b.id=a.branch_id JOIN auth.user_account u ON u.id=a.requested_by UNION ALL SELECT o.id,'overtime',o.employee_id,concat_ws(' ',e.first_name,e.last_name),e.employee_no,b.name,o.work_date,NULL,NULL,o.requested_minutes,o.approved_minutes,o.multiplier,o.reason,o.status,u.display_name,o.created_at FROM attendance.overtime_request o JOIN hr.employee e ON e.id=o.employee_id JOIN core.branch b ON b.id=o.branch_id JOIN auth.user_account u ON u.id=o.requested_by) x ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC""",c);await using var r=await q.ExecuteReaderAsync(ct);var a=new List<AttendanceRequestItem>();while(await r.ReadAsync(ct))a.Add(new(r.GetGuid(0),r.GetString(1),r.GetGuid(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetFieldValue<DateOnly>(6),DTO(r,7),DTO(r,8),NI(r,9),NI(r,10),r.IsDBNull(11)?null:r.GetDecimal(11),T(r,12),r.GetString(13),r.GetString(14),r.GetFieldValue<DateTimeOffset>(15)));return a;}

    public async Task SaveCalendarAsync(HolidayCalendarForm m,Guid actor,CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand(m.Id is null?"INSERT INTO attendance.holiday_calendar(branch_id,code,name,is_active,created_by,updated_by) VALUES(@branch,@code,@name,@active,@actor,@actor)":"UPDATE attendance.holiday_calendar SET branch_id=@branch,code=@code,name=@name,is_active=@active,updated_by=@actor WHERE id=@id",c);P(q,"branch",m.BranchId);q.Parameters.AddWithValue("code",m.Id is null?BusinessCode.New("CAL"):m.Code.Trim().ToUpperInvariant());q.Parameters.AddWithValue("name",m.Name.Trim());q.Parameters.AddWithValue("active",m.IsActive);q.Parameters.AddWithValue("actor",actor);if(m.Id is not null)q.Parameters.AddWithValue("id",m.Id.Value);await q.ExecuteNonQueryAsync(ct);}
    public async Task SaveHolidayAsync(HolidayForm m,Guid actor,CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand(m.Id is null?"INSERT INTO attendance.holiday(calendar_id,holiday_date,name,is_paid,created_by,updated_by) VALUES(@calendar,@date,@name,@paid,@actor,@actor)":"UPDATE attendance.holiday SET calendar_id=@calendar,holiday_date=@date,name=@name,is_paid=@paid,updated_by=@actor WHERE id=@id",c);q.Parameters.AddWithValue("calendar",m.CalendarId!.Value);q.Parameters.AddWithValue("date",m.HolidayDate);q.Parameters.AddWithValue("name",m.Name.Trim());q.Parameters.AddWithValue("paid",m.IsPaid);q.Parameters.AddWithValue("actor",actor);if(m.Id is not null)q.Parameters.AddWithValue("id",m.Id.Value);await q.ExecuteNonQueryAsync(ct);}
    public async Task SaveShiftAsync(ShiftForm m,Guid actor,CancellationToken ct=default){var minutes=(int)(m.EndTime.ToTimeSpan()-m.StartTime.ToTimeSpan()).TotalMinutes;if(m.CrossesMidnight||minutes<=0)minutes+=1440;minutes-=m.BreakMinutes;if(minutes<=0)throw new InvalidOperationException("Shift duration must be greater than break duration.");await using var c=await Open(ct);await using var q=new NpgsqlCommand(m.Id is null?"INSERT INTO attendance.shift(code,name,start_local_time,end_local_time,break_minutes,crosses_midnight,scheduled_minutes,is_flexible,is_active,created_by,updated_by) VALUES(@code,@name,@start,@end,@break,@cross,@minutes,@flex,@active,@actor,@actor)":"UPDATE attendance.shift SET code=@code,name=@name,start_local_time=@start,end_local_time=@end,break_minutes=@break,crosses_midnight=@cross,scheduled_minutes=@minutes,is_flexible=@flex,is_active=@active,updated_at=now(),updated_by=@actor WHERE id=@id",c);q.Parameters.AddWithValue("code",m.Id is null?BusinessCode.New("SHF"):m.Code.Trim().ToUpperInvariant());q.Parameters.AddWithValue("name",m.Name.Trim());q.Parameters.AddWithValue("start",m.StartTime);q.Parameters.AddWithValue("end",m.EndTime);q.Parameters.AddWithValue("break",m.BreakMinutes);q.Parameters.AddWithValue("cross",m.CrossesMidnight);q.Parameters.AddWithValue("minutes",minutes);q.Parameters.AddWithValue("flex",m.IsFlexible);q.Parameters.AddWithValue("active",m.IsActive);q.Parameters.AddWithValue("actor",actor);if(m.Id is not null)q.Parameters.AddWithValue("id",m.Id.Value);await q.ExecuteNonQueryAsync(ct);}
    public async Task SavePolicyAsync(AttendancePolicyForm m,Guid actor,CancellationToken ct=default){await using var c=await Open(ct);await using var q=new NpgsqlCommand(m.Id is null?"INSERT INTO attendance.attendance_policy(code,name,late_grace_minutes,early_out_grace_minutes,half_day_below_minutes,absent_below_minutes,overtime_after_minutes,overtime_rounding_minutes,overtime_multiplier,holiday_overtime_multiplier,weekly_off_days,require_overtime_approval,is_active,created_by,updated_by) VALUES(@code,@name,@late,@early,@half,@absent,@ot,@round,@multi,@holiday,@days,@approval,@active,@actor,@actor)":"UPDATE attendance.attendance_policy SET code=@code,name=@name,late_grace_minutes=@late,early_out_grace_minutes=@early,half_day_below_minutes=@half,absent_below_minutes=@absent,overtime_after_minutes=@ot,overtime_rounding_minutes=@round,overtime_multiplier=@multi,holiday_overtime_multiplier=@holiday,weekly_off_days=@days,require_overtime_approval=@approval,is_active=@active,updated_at=now(),updated_by=@actor WHERE id=@id",c);q.Parameters.AddWithValue("code",m.Id is null?BusinessCode.New("POL"):m.Code.Trim().ToUpperInvariant());q.Parameters.AddWithValue("name",m.Name.Trim());q.Parameters.AddWithValue("late",m.LateGraceMinutes);q.Parameters.AddWithValue("early",m.EarlyOutGraceMinutes);P(q,"half",m.HalfDayBelowMinutes);P(q,"absent",m.AbsentBelowMinutes);q.Parameters.AddWithValue("ot",m.OvertimeAfterMinutes);q.Parameters.AddWithValue("round",m.OvertimeRoundingMinutes);q.Parameters.AddWithValue("multi",m.OvertimeMultiplier);q.Parameters.AddWithValue("holiday",m.HolidayOvertimeMultiplier);q.Parameters.Add("days",NpgsqlDbType.Array|NpgsqlDbType.Smallint).Value=m.WeeklyOffDays;q.Parameters.AddWithValue("approval",m.RequireOvertimeApproval);q.Parameters.AddWithValue("active",m.IsActive);q.Parameters.AddWithValue("actor",actor);if(m.Id is not null)q.Parameters.AddWithValue("id",m.Id.Value);await q.ExecuteNonQueryAsync(ct);}
    public async Task SaveScheduleAsync(EmployeeScheduleForm m,Guid actor,CancellationToken ct=default){if(m.EffectiveTo<m.EffectiveFrom)throw new InvalidOperationException("Effective-to date cannot be before effective-from date.");await using var c=await Open(ct);await using var q=new NpgsqlCommand(m.Id is null?"INSERT INTO attendance.employee_schedule(employee_id,shift_id,policy_id,holiday_calendar_id,effective_from,effective_to,created_by,updated_by) VALUES(@employee,@shift,@policy,@calendar,@from,@to,@actor,@actor)":"UPDATE attendance.employee_schedule SET employee_id=@employee,shift_id=@shift,policy_id=@policy,holiday_calendar_id=@calendar,effective_from=@from,effective_to=@to,updated_by=@actor WHERE id=@id",c);q.Parameters.AddWithValue("employee",m.EmployeeId!.Value);q.Parameters.AddWithValue("shift",m.ShiftId!.Value);q.Parameters.AddWithValue("policy",m.PolicyId!.Value);P(q,"calendar",m.HolidayCalendarId);q.Parameters.AddWithValue("from",m.EffectiveFrom);P(q,"to",m.EffectiveTo);q.Parameters.AddWithValue("actor",actor);if(m.Id is not null)q.Parameters.AddWithValue("id",m.Id.Value);await q.ExecuteNonQueryAsync(ct);}
    public async Task SaveManualDayAsync(ManualAttendanceForm m,Guid actor,CancellationToken ct=default)
    {
        var first=Utc(m.FirstInLocal);var last=Utc(m.LastOutLocal);
        if(last<first)throw new InvalidOperationException("Clock-out cannot be before clock-in.");
        await using var c=await Open(ct);
        var rule=await GetRuleAsync(c,m.EmployeeId!.Value,m.WorkDate,ct)??throw new InvalidOperationException("Employee needs an active assignment and schedule for this date.");
        var result=Calculate(rule,m.WorkDate,first,last,m.BreakMinutes);
        await UpsertDayAsync(c,m.EmployeeId.Value,m.WorkDate,rule,result,first,last,m.BreakMinutes,"manual",actor,m.Reason.Trim(),m.Notes,ct);
    }

    public async Task GenerateRegisterAsync(DateOnly from,DateOnly to,Guid actor,CancellationToken ct=default)
    {
        if(to<from)throw new InvalidOperationException("To date cannot be before from date.");
        if((to.ToDateTime(TimeOnly.MinValue)-from.ToDateTime(TimeOnly.MinValue)).TotalDays>92)throw new InvalidOperationException("Generate a maximum of 93 days at one time.");
        await using var c=await Open(ct);
        for(var date=from;date<=to;date=date.AddDays(1))
        {
            await using var q=new NpgsqlCommand("""SELECT s.employee_id FROM attendance.employee_schedule s JOIN hr.employee e ON e.id=s.employee_id WHERE e.employment_status='active' AND s.effective_from<=@date AND (s.effective_to IS NULL OR s.effective_to>=@date)""",c);
            q.Parameters.AddWithValue("date",date);var ids=new List<Guid>();await using(var r=await q.ExecuteReaderAsync(ct)){while(await r.ReadAsync(ct))ids.Add(r.GetGuid(0));}
            foreach(var employee in ids)
            {
                var rule=await GetRuleAsync(c,employee,date,ct);if(rule is null)continue;
                await using var exists=new NpgsqlCommand("SELECT 1 FROM attendance.attendance_day WHERE employee_id=@employee AND work_date=@date",c);exists.Parameters.AddWithValue("employee",employee);exists.Parameters.AddWithValue("date",date);if(await exists.ExecuteScalarAsync(ct) is not null)continue;
                var status=await BaseStatusAsync(c,employee,rule,date,ct);
                var result=new DayResult(0,0,0,0,status);
                await UpsertDayAsync(c,employee,date,rule,result,null,null,0,"system",actor,null,null,ct);
            }
        }
    }

    public async Task SaveRequestAsync(AttendanceRequestForm m,Guid actor,CancellationToken ct=default)
    {
        var first=Utc(m.RequestedFirstInLocal);var last=Utc(m.RequestedLastOutLocal);if(last<first)throw new InvalidOperationException("Requested clock-out cannot be before clock-in.");
        await using var c=await Open(ct);await using var branch=new NpgsqlCommand("SELECT branch_id FROM hr.employee_assignment WHERE employee_id=@employee AND effective_from<=@date AND (effective_to IS NULL OR effective_to>=@date) ORDER BY effective_from DESC LIMIT 1",c);branch.Parameters.AddWithValue("employee",m.EmployeeId!.Value);branch.Parameters.AddWithValue("date",m.WorkDate);var branchId=await branch.ExecuteScalarAsync(ct) as Guid? ?? throw new InvalidOperationException("Employee has no active assignment for this date.");
        var sql=m.Kind=="overtime"?"INSERT INTO attendance.overtime_request(employee_id,branch_id,work_date,requested_minutes,multiplier,reason,requested_by,created_by,updated_by) VALUES(@employee,@branch,@date,@minutes,@multiplier,@reason,@actor,@actor,@actor)":"INSERT INTO attendance.adjustment_request(employee_id,branch_id,work_date,requested_first_in_at,requested_last_out_at,reason,requested_by,created_by,updated_by) VALUES(@employee,@branch,@date,@first,@last,@reason,@actor,@actor,@actor)";
        await using var q=new NpgsqlCommand(sql,c);q.Parameters.AddWithValue("employee",m.EmployeeId.Value);q.Parameters.AddWithValue("branch",branchId);q.Parameters.AddWithValue("date",m.WorkDate);q.Parameters.AddWithValue("reason",m.Reason.Trim());q.Parameters.AddWithValue("actor",actor);if(m.Kind=="overtime"){q.Parameters.AddWithValue("minutes",m.RequestedMinutes);q.Parameters.AddWithValue("multiplier",m.Multiplier);}else{P(q,"first",first);P(q,"last",last);}await q.ExecuteNonQueryAsync(ct);
    }

    public async Task DecideRequestAsync(Guid id,string kind,string status,Guid actor,int? approvedMinutes=null,CancellationToken ct=default)
    {
        if(status is not("approved" or "rejected"))throw new InvalidOperationException("Invalid decision.");
        Guid? employee=null;DateOnly workDate=default;DateTimeOffset? first=null,last=null;
        await using(var c=await Open(ct))
        {
            if(kind=="adjustment"&&status=="approved")
            {await using var read=new NpgsqlCommand("SELECT employee_id,work_date,requested_first_in_at,requested_last_out_at FROM attendance.adjustment_request WHERE id=@id",c);read.Parameters.AddWithValue("id",id);await using var r=await read.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){employee=r.GetGuid(0);workDate=r.GetFieldValue<DateOnly>(1);first=DTO(r,2);last=DTO(r,3);}}
            var sql=kind=="overtime"?"UPDATE attendance.overtime_request SET status=@status,approved_minutes=CASE WHEN @status='approved' THEN COALESCE(@minutes,requested_minutes) ELSE NULL END,decided_by=@actor,decided_at=now(),updated_at=now(),updated_by=@actor WHERE id=@id":"UPDATE attendance.adjustment_request SET status=@status,decided_by=@actor,decided_at=now(),updated_at=now(),updated_by=@actor WHERE id=@id";await using var q=new NpgsqlCommand(sql,c);q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("status",status);q.Parameters.AddWithValue("actor",actor);if(kind=="overtime")P(q,"minutes",approvedMinutes);await q.ExecuteNonQueryAsync(ct);
            if(kind=="overtime"&&status=="approved"){await using var apply=new NpgsqlCommand("UPDATE attendance.attendance_day d SET overtime_minutes=o.approved_minutes,updated_at=now(),updated_by=@actor FROM attendance.overtime_request o WHERE o.id=@id AND d.employee_id=o.employee_id AND d.work_date=o.work_date",c);apply.Parameters.AddWithValue("id",id);apply.Parameters.AddWithValue("actor",actor);await apply.ExecuteNonQueryAsync(ct);}
        }
        if(employee is not null){var localFirst=first?.ToOffset(TimeSpan.FromHours(5)).DateTime;var localLast=last?.ToOffset(TimeSpan.FromHours(5)).DateTime;await SaveManualDayAsync(new(){EmployeeId=employee,WorkDate=workDate,FirstInLocal=localFirst,LastOutLocal=localLast,Reason="Approved attendance adjustment"},actor,ct);}
    }

    private static async Task<DayRule?> GetRuleAsync(NpgsqlConnection c,Guid employee,DateOnly date,CancellationToken ct)
    {await using var q=new NpgsqlCommand("""SELECT a.branch_id,a.department_id,s.shift_id,s.policy_id,s.holiday_calendar_id,sh.start_local_time,sh.end_local_time,sh.crosses_midnight,sh.scheduled_minutes,sh.break_minutes,p.late_grace_minutes,p.early_out_grace_minutes,p.half_day_below_minutes,p.absent_below_minutes,p.overtime_after_minutes,p.overtime_rounding_minutes,p.weekly_off_days FROM LATERAL(SELECT branch_id,department_id FROM hr.employee_assignment WHERE employee_id=@employee AND effective_from<=@date AND(effective_to IS NULL OR effective_to>=@date) ORDER BY effective_from DESC LIMIT 1)a JOIN LATERAL(SELECT shift_id,policy_id,holiday_calendar_id FROM attendance.employee_schedule WHERE employee_id=@employee AND effective_from<=@date AND(effective_to IS NULL OR effective_to>=@date) ORDER BY effective_from DESC LIMIT 1)s ON true JOIN attendance.shift sh ON sh.id=s.shift_id JOIN attendance.attendance_policy p ON p.id=s.policy_id""",c);q.Parameters.AddWithValue("employee",employee);q.Parameters.AddWithValue("date",date);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetGuid(3),G(r,4),r.GetFieldValue<TimeOnly>(5),r.GetFieldValue<TimeOnly>(6),r.GetBoolean(7),r.GetInt32(8),r.GetInt32(9),r.GetInt32(10),r.GetInt32(11),NI(r,12),NI(r,13),r.GetInt32(14),r.GetInt32(15),r.GetFieldValue<short[]>(16)):null;}
    private static DayResult Calculate(DayRule r,DateOnly date,DateTimeOffset? first,DateTimeOffset? last,int enteredBreak)
    {if(first is null&&last is null)return new(0,0,0,0,"absent");if(first is null||last is null)return new(0,0,0,0,"missing_punch");var start=new DateTimeOffset(date.ToDateTime(r.Start),TimeSpan.FromHours(5)).ToUniversalTime();var end=new DateTimeOffset(date.ToDateTime(r.End).AddDays(r.Crosses?1:0),TimeSpan.FromHours(5)).ToUniversalTime();if(end<=start)end=end.AddDays(1);var breakMinutes=enteredBreak>0?enteredBreak:r.Break;var worked=Math.Max(0,(int)(last.Value-first.Value).TotalMinutes-breakMinutes);var late=Math.Max(0,(int)(first.Value-start).TotalMinutes-r.LateGrace);var early=Math.Max(0,(int)(end-last.Value).TotalMinutes-r.EarlyGrace);var extra=Math.Max(0,(int)(last.Value-end).TotalMinutes);var overtime=extra<r.OvertimeAfter?0:(extra/r.Rounding)*r.Rounding;var status=r.AbsentBelow is not null&&worked<r.AbsentBelow?"absent":r.HalfBelow is not null&&worked<r.HalfBelow?"half_day":late>0?"late":"present";return new(worked,late,early,overtime,status);}
    private static async Task<string> BaseStatusAsync(NpgsqlConnection c,Guid employee,DayRule r,DateOnly date,CancellationToken ct)
    {var iso=(short)(((int)date.DayOfWeek+6)%7+1);if(r.WeeklyOff.Contains(iso))return "weekly_off";if(r.Calendar is not null){await using var h=new NpgsqlCommand("SELECT 1 FROM attendance.holiday WHERE calendar_id=@calendar AND holiday_date=@date",c);h.Parameters.AddWithValue("calendar",r.Calendar.Value);h.Parameters.AddWithValue("date",date);if(await h.ExecuteScalarAsync(ct) is not null)return "holiday";}await using var l=new NpgsqlCommand("SELECT 1 FROM leave_mgmt.leave_request WHERE employee_id=@employee AND status='approved' AND @date BETWEEN start_date AND end_date",c);l.Parameters.AddWithValue("employee",employee);l.Parameters.AddWithValue("date",date);if(await l.ExecuteScalarAsync(ct) is not null)return "leave";return "absent";}
    private static async Task UpsertDayAsync(NpgsqlConnection c,Guid employee,DateOnly date,DayRule r,DayResult x,DateTimeOffset? first,DateTimeOffset? last,int breakMinutes,string source,Guid actor,string? reason,string? notes,CancellationToken ct)
    {await using var q=new NpgsqlCommand("""INSERT INTO attendance.attendance_day(employee_id,branch_id,department_id,work_date,shift_id,policy_id,first_in_at,last_out_at,scheduled_minutes,worked_minutes,late_minutes,early_out_minutes,overtime_minutes,break_minutes,status,entry_source,manual_entry_by,manual_entry_reason,notes,created_by,updated_by) VALUES(@employee,@branch,@department,@date,@shift,@policy,@first,@last,@scheduled,@worked,@late,@early,@overtime,@break,@status,@source,@manual_by,@reason,@notes,@actor,@actor) ON CONFLICT(employee_id,work_date) DO UPDATE SET branch_id=EXCLUDED.branch_id,department_id=EXCLUDED.department_id,shift_id=EXCLUDED.shift_id,policy_id=EXCLUDED.policy_id,first_in_at=EXCLUDED.first_in_at,last_out_at=EXCLUDED.last_out_at,scheduled_minutes=EXCLUDED.scheduled_minutes,worked_minutes=EXCLUDED.worked_minutes,late_minutes=EXCLUDED.late_minutes,early_out_minutes=EXCLUDED.early_out_minutes,overtime_minutes=EXCLUDED.overtime_minutes,break_minutes=EXCLUDED.break_minutes,status=EXCLUDED.status,entry_source=EXCLUDED.entry_source,manual_entry_by=EXCLUDED.manual_entry_by,manual_entry_reason=EXCLUDED.manual_entry_reason,notes=EXCLUDED.notes,calculated_at=now(),updated_at=now(),updated_by=@actor""",c);q.Parameters.AddWithValue("employee",employee);q.Parameters.AddWithValue("branch",r.Branch);q.Parameters.AddWithValue("department",r.Department);q.Parameters.AddWithValue("date",date);q.Parameters.AddWithValue("shift",r.Shift);q.Parameters.AddWithValue("policy",r.Policy);P(q,"first",first);P(q,"last",last);q.Parameters.AddWithValue("scheduled",r.Scheduled);q.Parameters.AddWithValue("worked",x.Worked);q.Parameters.AddWithValue("late",x.Late);q.Parameters.AddWithValue("early",x.Early);q.Parameters.AddWithValue("overtime",x.Overtime);q.Parameters.AddWithValue("break",breakMinutes>0?breakMinutes:r.Break);q.Parameters.AddWithValue("status",x.Status);q.Parameters.AddWithValue("source",source);P(q,"manual_by",source=="manual"?actor:null);P(q,"reason",source=="manual"?reason:null);P(q,"notes",notes);q.Parameters.AddWithValue("actor",actor);await q.ExecuteNonQueryAsync(ct);}
    private sealed record DayRule(Guid Branch,Guid Department,Guid Shift,Guid Policy,Guid? Calendar,TimeOnly Start,TimeOnly End,bool Crosses,int Scheduled,int Break,int LateGrace,int EarlyGrace,int? HalfBelow,int? AbsentBelow,int OvertimeAfter,int Rounding,short[] WeeklyOff);
    private sealed record DayResult(int Worked,int Late,int Early,int Overtime,string Status);

    private static async Task<NpgsqlConnection> Open(CancellationToken ct){var c=new NpgsqlConnection(StaticConnection.conn);await c.OpenAsync(ct);return c;}private static string? T(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static Guid? G(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetGuid(i);private static int? NI(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetInt32(i);private static DateOnly? ND(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetFieldValue<DateOnly>(i);private static DateTimeOffset? DTO(NpgsqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetFieldValue<DateTimeOffset>(i);private static void P(NpgsqlCommand q,string n,object? v)=>q.Parameters.AddWithValue(n,v??DBNull.Value);private static DateTimeOffset? Utc(DateTime? x)=>x is null?null:new DateTimeOffset(DateTime.SpecifyKind(x.Value,DateTimeKind.Unspecified),TimeSpan.FromHours(5)).ToUniversalTime();
}
